#!/bin/bash

PYTHONPATH=/your/path/to/myhubot/node_modules/hubot-script-shellcmd/bash/handlers/ python /your/path/to/myhubot/node_modules/hubot-script-shellcmd/bash/handlers/createpretext.py $1 $2 $3 $4 $5
